### ISSUE TITLE
关于priority问题(顺便来抢个first issue(   )

### ISSUE THREAD

**Issue by xryze-cry** [SEVEN-6174/zhenxun_plugin_guessname#1]
在运行时出现了
[DEBUG] nonebot | Checking for matchers in priority 5...
然后开始超时循环没动静了
问，如何解决，急急急急急急

**Comment by SEVEN-6174** [comment]
看看目录结构

**Comment by xryze-cry** [comment]
大概是这样的
[https://i.postimg.cc/BvJGqS2G/2023-07-16-175212.png](url)
[https://i.postimg.cc/sX6BY03v/2023-07-16-175344.png](url)

**Comment by SEVEN-6174** [comment]
这个分辨率
emmm?
太糊了吧啊喂

**Comment by SEVEN-6174** [comment]
> 大概是这样的 [https://i.postimg.cc/BvJGqS2G/2023-07-16-175212.png](url) [https://i.postimg.cc/sX6BY03v/2023-07-16-175344.png](url)

那么bot.py文件能否看一下

**Comment by xryze-cry** [comment]
完全没有改动（
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import nonebot
from nonebot.adapters.onebot.v11 import Adapter as ONEBOT_V11Adapter

# Custom your logger
# 
# from nonebot.log import logger, default_format
# logger.add("error.log",
#            rotation="00:00",
#            diagnose=False,
#            level="ERROR",
#            format=default_format)

# You can pass some keyword args config to init function
nonebot.init()
app = nonebot.get_asgi()

driver = nonebot.get_driver()
driver.register_adapter(ONEBOT_V11Adapter)


# Please DO NOT modify this file unless you know what you are doing!
# As an alternative, you should use command `nb` or modify `pyproject.toml` to load plugins
nonebot.load_from_toml("pyproject.toml")

# Modify some config / config depends on loaded configs
# 
# config = driver.config
# do something...


if __name__ == "__main__":
    nonebot.logger.warning("Always use `nb run` to start the bot instead of manually running!")
    nonebot.run(app="__mp_main__:app")
```

**Comment by SEVEN-6174** [comment]
> 完全没有改动（
> 
> ```
> #!/usr/bin/env python3
> # -*- coding: utf-8 -*-
> 
> import nonebot
> from nonebot.adapters.onebot.v11 import Adapter as ONEBOT_V11Adapter
> 
> # Custom your logger
> # 
> # from nonebot.log import logger, default_format
> # logger.add("error.log",
> #            rotation="00:00",
> #            diagnose=False,
> #            level="ERROR",
> #            format=default_format)
> 
> # You can pass some keyword args config to init function
> nonebot.init()
> app = nonebot.get_asgi()
> 
> driver = nonebot.get_driver()
> driver.register_adapter(ONEBOT_V11Adapter)
> 
> 
> # Please DO NOT modify this file unless you know what you are doing!
> # As an alternative, you should use command `nb` or modify `pyproject.toml` to load plugins
> nonebot.load_from_toml("pyproject.toml")
> 
> # Modify some config / config depends on loaded configs
> # 
> # config = driver.config
> # do something...
> 
> 
> if __name__ == "__main__":
>     nonebot.logger.warning("Always use `nb run` to start the bot instead of manually running!")
>     nonebot.run(app="__mp_main__:app")
> ```

那么pyproject.toml里面有没有添加插件信息

如

[tool.nonebot]

plugin_dirs = ["src\plugins"]

或直接加载插件

[tool.nonebot]

plugins = ["src.plugins.guessname"]

**Comment by xryze-cry** [comment]
已经添加了，并且在nb run之后会有加载成功的提示

**Comment by xryze-cry** [comment]
已经添加了，并且在nb run之后会有加载成功的提示

**Comment by SEVEN-6174** [comment]
> 已经添加了，并且在nb run之后会有加载成功的提示

怪欸
那不知道怎么办了

**Comment by xryze-cry** [comment]
我去问了并且实验了一下
发现加了“/”之后可以用了
是不是你env里面改了什么东西？command指令头这样的？

**Comment by SEVEN-6174** [comment]
> 我去问了并且实验了一下 发现加了“/”之后可以用了 是不是你env里面改了什么东西？command指令头这样的？

斯
我是COMMAND_START=[""]
